services:
  db-primary:
    image: postgres:16
    container_name: url-shortener-db-primary
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres_primary_data:/var/lib/postgresql
  db-replica:
    image: postgres:16
    container_name: url-shortener-db-replica
    environment:
      POSTGRES_USER: ${PGREPLICA_USER}
      POSTGRES_PASSWORD: ${PGREPLICA_PASSWORD}
      POSTGRES_DB: ${PGREPLICA_DATABASE}
    ports:
      - "${PGREPLICA_PORT}:5432"
    volumes:
      - postgres_replica_data:/var/lib/postgresql
  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_primary_data:
  postgres_replica_data:
  redis_data:
